swagger: '2.0'
info:
  version: '0.1'
  title: Members management system
host: wolbodo.dxlb.nl
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /token:
    post: 
      description: Generate a token
      parameters:
        - in: body
          name: body
          description: User login credentials
          required: true
          schema: 
            $ref: '#/definitions/Credentials'
      responses:
        200: 
          description: Valid login attempt
          schema: 
            $ref: '#/definitions/Token'
  /self:
    get:
      description: Returns the user info
      parameters:
        - in: header
          name: Authorization
          description:  A base64 hash of the JSON encoded token.
          type: string
      responses:
        200:
          description: The user info
          schema: 
            type: object

definitions:
  Credentials:
    type: object
    required: 
      - user
      - password
    properties:
      user: 
        type: string
      password:
        type: string
  Token:
    description: A token stating the server has authenticated the user.
    type: object
    required: 
      - message
      - signature
    properties:
      message:
        type: object
        properties:
          timestamp:
            type: integer
          id:
            type: integer
      signature:
        type: string